spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_sync_blog?useSSL=false&serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password : ${DB_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ap-northeast-2


logging:
  level:
    org.hibernate.SQL: debug

